apiVersion: v1
kind: Service
metadata:
  name: sporty-rest-gateway
  namespace: sporty
spec:
  selector:
    app: sporty-rest-gateway
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP
