apiVersion: v1
kind: Service
metadata:
  name: sporty-rest-producer
  namespace: sporty
spec:
  selector:
    app: sporty-rest-producer
  ports:
  - name: http
    port: 8081
    targetPort: 8081
  type: ClusterIP
